INSERT INTO book(id,name,author,price) VALUES (1,'Spring In Action:Covers Spring 3.0','Craig Walls', 400);
INSERT INTO book(id,name,author,price) VALUES (2,'Spring Batch In Action','Arnaud Cogoluegnes', 500);
INSERT INTO book(id,name,author,price) VALUES (3,'Spring Book','Rod', 300);
INSERT INTO book(id,name,author,price) VALUES (4,'Java Book','test', 100);
INSERT INTO book(id,name,author,price) VALUES (5,'Spring Boot Application','test', 200);
INSERT INTO book(id,name,author,price) VALUES (6,'Learn Spring Data JPA','test', 300);
INSERT INTO book(id,name,author,price) VALUES (7,'Hibernat in Action','Gavin King', 300);
INSERT INTO book(id,name,author,price) VALUES (8,'JSF in Action','Kit', 400);
INSERT INTO book(id,name,author,price) VALUES (9,'Java Interview Questions','Subramanian', 450);
INSERT INTO book(id,name,author,price) VALUES (10,'Java Complete Reference','Herbert', 450);